// Auto-generated by genVerilog.py from MODULE_GRAPH.json + NET_GRAPH.json.
// Power/ground nets are already absent from MODULE_GRAPH.json's nodes/edges
// (dropped upstream by moduleGraph.py); this file never reintroduces them.

module adder_demo (
    input  A,
    input  B,
    input  clk,
    input  en,
    input  rst_n,
    output S
);

wire net_1542;
wire net_1646;
wire net_1710;
wire net_1811;
wire net_1821;
wire net_1829;
wire net_1881;
wire net_1885;
wire net_1888;
wire net_1889;
wire net_1890;
wire net_1891;
wire net_1892;
wire net_1893;
wire net_1894;
wire net_1895;
wire net_1896;
wire net_1897;
wire net_1900;
wire net_1908;
wire net_1918;
wire net_1946;
wire net_1947;
wire net_1948;
wire net_1949;
wire net_1950;
wire net_1951;
wire net_1954;
wire net_1957;
wire net_1965;
wire net_1968;
wire net_1976;
wire net_1988;
wire net_1989;
wire net_1999;
wire net_2000;
wire net_2001;
wire net_2002;
wire net_2003;
wire net_2007;
wire net_2012;
wire net_2022;
wire net_2025;
wire net_2026;
wire net_2027;
wire net_2030;
wire net_2031;
wire net_2034;
wire net_2037;
wire net_2039;
wire net_2045;
wire net_2046;
wire net_2048;
wire net_2051;
wire net_2052;
wire net_2057;
wire net_2058;
wire net_2059;
wire net_2061;
wire net_2062;
wire net_2063;
wire net_2065;
wire net_2066;
wire net_2067;
wire net_2069;
wire net_2070;
wire net_2071;
wire net_2072;
wire net_2074;
wire net_2085;
wire net_2088;
wire net_2092;
wire net_2096;
wire net_3493;
wire net_5645;
wire net_5744;
wire net_5782;
wire net_9400;

sky130_fd_sc_hd__nand2_2 u1002 (
    .A(net_1988),
    .B(net_2012),
    .Y(net_2022)
);

sky130_fd_sc_hd__and2_2 u1011 (
    .A(net_2030),
    .B(net_2031),
    .X(net_2034)
);

sky130_fd_sc_hd__a31o_2 u1048 (
    .A1(net_1988),
    .A2(net_2012),
    .A3(net_2026),
    .B1(net_2025),
    .X(net_2027)
);

sky130_fd_sc_hd__xnor2_2 u1052 (
    .A(net_2022),
    .B(net_2026),
    .Y(net_2096)
);

sky130_fd_sc_hd__or2_2 u1069 (
    .A(net_1988),
    .B(net_2012),
    .X(net_2074)
);

sky130_fd_sc_hd__and2_2 u1070 (
    .A(net_2007),
    .B(net_1881),
    .X(net_2046)
);

sky130_fd_sc_hd__and3_2 u108 (
    .A(net_1893),
    .B(net_1894),
    .C(net_1895),
    .X(net_1896)
);

sky130_fd_sc_hd__clkbuf_16 u136 (
    .A(net_1885),
    .X(net_1918)
);

sky130_fd_sc_hd__mux2_1 u137 (
    .A0(net_1957),
    .A1(net_1542),
    .S(en),
    .X(net_1948)
);

sky130_fd_sc_hd__mux2_1 u138 (
    .A0(net_1881),
    .A1(net_1957),
    .S(en),
    .X(net_1949)
);

sky130_fd_sc_hd__mux2_1 u139 (
    .A0(net_2085),
    .A1(net_1900),
    .S(en),
    .X(net_1951)
);

sky130_fd_sc_hd__mux2_1 u140 (
    .A0(net_2012),
    .A1(A),
    .S(en),
    .X(net_3493)
);

sky130_fd_sc_hd__dfrtp_2 u141 (
    .CLK(net_1918),
    .D(net_1950),
    .Q(net_1900),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u142 (
    .CLK(net_1918),
    .D(net_1949),
    .Q(net_1881),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u146 (
    .CLK(net_1918),
    .D(net_1948),
    .Q(net_1957),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u180 (
    .CLK(net_1918),
    .D(net_1947),
    .Q(net_1542),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u181 (
    .CLK(net_1918),
    .D(net_3493),
    .Q(net_2012),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u182 (
    .CLK(net_1918),
    .D(net_1951),
    .Q(net_2085),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__mux2_1 u210 (
    .A0(net_1900),
    .A1(net_1881),
    .S(en),
    .X(net_1950)
);

sky130_fd_sc_hd__mux2_1 u234 (
    .A0(net_1542),
    .A1(net_1811),
    .S(en),
    .X(net_1947)
);

sky130_fd_sc_hd__mux2_1 u274 (
    .A0(net_1908),
    .A1(net_2085),
    .S(en),
    .X(net_1954)
);

sky130_fd_sc_hd__mux2_1 u339 (
    .A0(net_1811),
    .A1(net_2012),
    .S(en),
    .X(net_1946)
);

sky130_fd_sc_hd__dfrtp_2 u348 (
    .CLK(net_1918),
    .D(net_1954),
    .Q(net_1908),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u368 (
    .CLK(net_1918),
    .D(net_1946),
    .Q(net_1811),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__mux2_1 u369 (
    .A0(net_2088),
    .A1(net_1989),
    .S(en),
    .X(net_5645)
);

sky130_fd_sc_hd__mux2_1 u378 (
    .A0(net_1989),
    .A1(net_1988),
    .S(en),
    .X(net_5744)
);

sky130_fd_sc_hd__mux2_1 u379 (
    .A0(net_1988),
    .A1(B),
    .S(en),
    .X(net_5782)
);

sky130_fd_sc_hd__dfrtp_2 u385 (
    .CLK(net_1976),
    .D(net_2002),
    .Q(net_1968),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u386 (
    .CLK(net_1976),
    .D(net_1999),
    .Q(net_2092),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u387 (
    .CLK(net_1976),
    .D(net_2003),
    .Q(net_1646),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u388 (
    .CLK(net_1976),
    .D(net_5645),
    .Q(net_2088),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__mux2_1 u404 (
    .A0(net_1646),
    .A1(net_1968),
    .S(en),
    .X(net_2003)
);

sky130_fd_sc_hd__mux2_1 u418 (
    .A0(net_2007),
    .A1(net_2092),
    .S(en),
    .X(net_2000)
);

sky130_fd_sc_hd__mux2_1 u426 (
    .A0(net_1968),
    .A1(net_1965),
    .S(en),
    .X(net_2002)
);

sky130_fd_sc_hd__dfrtp_2 u433 (
    .CLK(net_1976),
    .D(net_5744),
    .Q(net_1989),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__clkbuf_16 u443 (
    .A(net_1885),
    .X(net_1976)
);

sky130_fd_sc_hd__dfrtp_2 u453 (
    .CLK(net_1976),
    .D(net_2001),
    .Q(net_1965),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u541 (
    .CLK(net_1976),
    .D(net_5782),
    .Q(net_1988),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__dfrtp_2 u554 (
    .CLK(net_1976),
    .D(net_2000),
    .Q(net_2007),
    .RESET_B(rst_n)
);

sky130_fd_sc_hd__mux2_1 u596 (
    .A0(net_1965),
    .A1(net_2007),
    .S(en),
    .X(net_2001)
);

sky130_fd_sc_hd__clkbuf_16 u5 (
    .A(clk),
    .X(net_1885)
);

sky130_fd_sc_hd__mux2_1 u603 (
    .A0(net_2092),
    .A1(net_2088),
    .S(en),
    .X(net_1999)
);

sky130_fd_sc_hd__a31o_2 u613 (
    .A1(net_2088),
    .A2(net_1542),
    .A3(net_2037),
    .B1(net_2039),
    .X(net_2052)
);

sky130_fd_sc_hd__nor2_2 u616 (
    .A(net_1646),
    .B(net_1908),
    .Y(net_2070)
);

sky130_fd_sc_hd__nor2_2 u617 (
    .A(net_2092),
    .B(net_1957),
    .Y(net_1710)
);

sky130_fd_sc_hd__nor2_2 u618 (
    .A(net_1965),
    .B(net_1900),
    .Y(net_2058)
);

sky130_fd_sc_hd__nor2_2 u619 (
    .A(net_2046),
    .B(net_2048),
    .Y(net_2051)
);

sky130_fd_sc_hd__a21boi_2 u622 (
    .A1(net_1821),
    .A2(net_2067),
    .B1_N(net_2063),
    .Y(net_2072)
);

sky130_fd_sc_hd__o21bai_2 u623 (
    .A1(net_2070),
    .A2(net_2072),
    .B1_N(net_2069),
    .Y(net_1895)
);

sky130_fd_sc_hd__and2_2 u629 (
    .A(net_2022),
    .B(net_2074),
    .X(net_1888)
);

sky130_fd_sc_hd__and2_2 u630 (
    .A(net_1646),
    .B(net_1908),
    .X(net_2069)
);

sky130_fd_sc_hd__xor2_2 u631 (
    .A(net_1989),
    .B(net_1811),
    .X(net_2026)
);

sky130_fd_sc_hd__xor2_2 u632 (
    .A(net_2062),
    .B(net_9400),
    .X(net_1892)
);

sky130_fd_sc_hd__xor2_2 u633 (
    .A(net_2051),
    .B(net_2057),
    .X(net_1891)
);

sky130_fd_sc_hd__xor2_2 u634 (
    .A(net_2027),
    .B(net_2034),
    .X(net_1889)
);

sky130_fd_sc_hd__a31o_2 u635 (
    .A1(net_2051),
    .A2(net_2057),
    .A3(net_2062),
    .B1(net_2066),
    .X(net_2067)
);

sky130_fd_sc_hd__or2_2 u636 (
    .A(net_1968),
    .B(net_2085),
    .X(net_1821)
);

sky130_fd_sc_hd__and2_2 u639 (
    .A(net_1965),
    .B(net_1900),
    .X(net_2061)
);

sky130_fd_sc_hd__and4bb_2 u659 (
    .A_N(net_2096),
    .B_N(net_1888),
    .C(net_1896),
    .D(net_1897),
    .X(S)
);

sky130_fd_sc_hd__or2_2 u685 (
    .A(net_2088),
    .B(net_1542),
    .X(net_2030)
);

sky130_fd_sc_hd__and4bb_2 u6 (
    .A_N(net_1890),
    .B_N(net_1889),
    .C(net_1891),
    .D(net_1892),
    .X(net_1897)
);

sky130_fd_sc_hd__a21bo_2 u707 (
    .A1(net_2027),
    .A2(net_2034),
    .B1_N(net_2031),
    .X(net_2045)
);

sky130_fd_sc_hd__and2_2 u711 (
    .A(net_2092),
    .B(net_1957),
    .X(net_2039)
);

sky130_fd_sc_hd__nor2_2 u761 (
    .A(net_2058),
    .B(net_2061),
    .Y(net_2062)
);

sky130_fd_sc_hd__nor2_2 u765 (
    .A(net_1710),
    .B(net_2039),
    .Y(net_1829)
);

sky130_fd_sc_hd__a21o_2 u781 (
    .A1(net_2051),
    .A2(net_2057),
    .B1(net_2046),
    .X(net_9400)
);

sky130_fd_sc_hd__or2_2 u841 (
    .A(net_1965),
    .B(net_1900),
    .X(net_2059)
);

sky130_fd_sc_hd__nor2_2 u844 (
    .A(net_2007),
    .B(net_1881),
    .Y(net_2048)
);

sky130_fd_sc_hd__nand2_2 u852 (
    .A(net_2063),
    .B(net_1821),
    .Y(net_2065)
);

sky130_fd_sc_hd__and2_2 u864 (
    .A(net_1989),
    .B(net_1811),
    .X(net_2025)
);

sky130_fd_sc_hd__a31o_2 u866 (
    .A1(net_2007),
    .A2(net_1881),
    .A3(net_2059),
    .B1(net_2061),
    .X(net_2066)
);

sky130_fd_sc_hd__or2_2 u895 (
    .A(net_2092),
    .B(net_1957),
    .X(net_2037)
);

sky130_fd_sc_hd__xnor2_2 u900 (
    .A(net_2065),
    .B(net_2067),
    .Y(net_1893)
);

sky130_fd_sc_hd__a31o_2 u917 (
    .A1(net_2027),
    .A2(net_2034),
    .A3(net_1829),
    .B1(net_2052),
    .X(net_2057)
);

sky130_fd_sc_hd__xor2_2 u972 (
    .A(net_1829),
    .B(net_2045),
    .X(net_1890)
);

sky130_fd_sc_hd__xnor2_2 u975 (
    .A(net_2071),
    .B(net_2072),
    .Y(net_1894)
);

sky130_fd_sc_hd__nand2_2 u976 (
    .A(net_1968),
    .B(net_2085),
    .Y(net_2063)
);

sky130_fd_sc_hd__nand2_2 u978 (
    .A(net_2088),
    .B(net_1542),
    .Y(net_2031)
);

sky130_fd_sc_hd__nor2_2 u989 (
    .A(net_2069),
    .B(net_2070),
    .Y(net_2071)
);

endmodule // adder_demo
