// Auto-generated by genBlockVerilog.py from BLOCK_MATCH.json
// (+ MODULE_GRAPH.json for the gate-level wiring).
// Same gates as adder_demo.v, regrouped into one module per structure
// blockMatch.py identified, and rewired with the names it recovered.

// 8-bit adder (8 carry merges, 8 sum bits) + compare/equality tree (3 reduce stages)
module adder_compare (
    input  a_reg0,
    input  a_reg1,
    input  a_reg2,
    input  a_reg3,
    input  a_reg4,
    input  a_reg5,
    input  a_reg6,
    input  a_reg7,
    input  b_reg0,
    input  b_reg1,
    input  b_reg2,
    input  b_reg3,
    input  b_reg4,
    input  b_reg5,
    input  b_reg6,
    input  b_reg7,
    output S
);

wire carry0;
wire carry1;
wire carry2;
wire carry3;
wire carry4;
wire carry5;
wire carry6;
wire carry7;
wire eq0;
wire eq1;
wire g0;
wire g1;
wire g2;
wire g3;
wire g4;
wire g5;
wire g6;
wire g7;
wire p0;
wire p2;
wire p3;
wire p3_dual;
wire p4;
wire p5;
wire p5_dual;
wire p6;
wire p7;
wire sumbit0;
wire sumbit1;
wire sumbit2;
wire sumbit3;
wire sumbit4;
wire sumbit5;
wire sumbit6;
wire sumbit7;
wire xsum0;
wire xsum1;
wire xsum2;
wire xsum3;
wire xsum4;
wire xsum5;
wire xsum6;
wire xsum7;

// ---- ADDER_SLICE [bit 0] (function): carry-lookahead bit slice: generate, propagate, and (where built) the half-sum of one operand bit pair
sky130_fd_sc_hd__nand2_2 u1002 (   // ADDER_SLICE.g
    .A(b_reg0),
    .B(a_reg0),
    .Y(g0)
);
sky130_fd_sc_hd__or2_2 u1069 (   // ADDER_SLICE.p
    .A(b_reg0),
    .B(a_reg0),
    .X(p0)
);
sky130_fd_sc_hd__and2_2 u629 (   // ADDER_SLICE.xs
    .A(g0),
    .B(p0),
    .X(xsum0)
);

// ---- HALF_ADDER [bit 1] (function): sum + carry over two operand bits (adder LSB / incrementer)
sky130_fd_sc_hd__xor2_2 u631 (   // HALF_ADDER.sum
    .A(b_reg1),
    .B(a_reg1),
    .X(xsum1)
);
sky130_fd_sc_hd__and2_2 u864 (   // HALF_ADDER.carry
    .A(b_reg1),
    .B(a_reg1),
    .X(g1)
);

// ---- ADDER_SLICE [bit 2]
sky130_fd_sc_hd__nand2_2 u978 (   // ADDER_SLICE.g
    .A(b_reg2),
    .B(a_reg2),
    .Y(g2)
);
sky130_fd_sc_hd__or2_2 u685 (   // ADDER_SLICE.p
    .A(b_reg2),
    .B(a_reg2),
    .X(p2)
);
sky130_fd_sc_hd__and2_2 u1011 (   // ADDER_SLICE.xs
    .A(p2),
    .B(g2),
    .X(xsum2)
);

// ---- ADDER_SLICE [bit 3]
sky130_fd_sc_hd__and2_2 u711 (   // ADDER_SLICE.g
    .A(b_reg3),
    .B(a_reg3),
    .X(g3)
);
sky130_fd_sc_hd__nor2_2 u617 (   // ADDER_SLICE.p
    .A(b_reg3),
    .B(a_reg3),
    .Y(p3)
);
sky130_fd_sc_hd__or2_2 u895 (   // ADDER_SLICE.p2
    .A(b_reg3),
    .B(a_reg3),
    .X(p3_dual)
);
sky130_fd_sc_hd__nor2_2 u765 (   // ADDER_SLICE.xs
    .A(p3),
    .B(g3),
    .Y(xsum3)
);

// ---- ADDER_SLICE [bit 4]
sky130_fd_sc_hd__and2_2 u1070 (   // ADDER_SLICE.g
    .A(b_reg4),
    .B(a_reg4),
    .X(g4)
);
sky130_fd_sc_hd__nor2_2 u844 (   // ADDER_SLICE.p
    .A(b_reg4),
    .B(a_reg4),
    .Y(p4)
);
sky130_fd_sc_hd__nor2_2 u619 (   // ADDER_SLICE.xs
    .A(g4),
    .B(p4),
    .Y(xsum4)
);

// ---- ADDER_SLICE [bit 5]
sky130_fd_sc_hd__and2_2 u639 (   // ADDER_SLICE.g
    .A(b_reg5),
    .B(a_reg5),
    .X(g5)
);
sky130_fd_sc_hd__nor2_2 u618 (   // ADDER_SLICE.p
    .A(b_reg5),
    .B(a_reg5),
    .Y(p5)
);
sky130_fd_sc_hd__or2_2 u841 (   // ADDER_SLICE.p2
    .A(b_reg5),
    .B(a_reg5),
    .X(p5_dual)
);
sky130_fd_sc_hd__nor2_2 u761 (   // ADDER_SLICE.xs
    .A(p5),
    .B(g5),
    .Y(xsum5)
);

// ---- ADDER_SLICE [bit 6]
sky130_fd_sc_hd__nand2_2 u976 (   // ADDER_SLICE.g
    .A(b_reg6),
    .B(a_reg6),
    .Y(g6)
);
sky130_fd_sc_hd__or2_2 u636 (   // ADDER_SLICE.p
    .A(b_reg6),
    .B(a_reg6),
    .X(p6)
);
sky130_fd_sc_hd__nand2_2 u852 (   // ADDER_SLICE.xs
    .A(g6),
    .B(p6),
    .Y(xsum6)
);

// ---- ADDER_SLICE [bit 7]
sky130_fd_sc_hd__and2_2 u630 (   // ADDER_SLICE.g
    .A(b_reg7),
    .B(a_reg7),
    .X(g7)
);
sky130_fd_sc_hd__nor2_2 u616 (   // ADDER_SLICE.p
    .A(b_reg7),
    .B(a_reg7),
    .Y(p7)
);
sky130_fd_sc_hd__nor2_2 u989 (   // ADDER_SLICE.xs
    .A(g7),
    .B(p7),
    .Y(xsum7)
);

// ---- CARRY_MERGE (context): AND-OR compound folding a bit slice's generate term into the carry chain
sky130_fd_sc_hd__a31o_2 u1048 (   // CARRY_MERGE.cell
    .A1(b_reg0),
    .A2(a_reg0),
    .A3(xsum1),
    .B1(g1),
    .X(carry0)
);

// ---- SUM_BIT (context): a sum bit of the adder: combines slice terms and the carry into it, and is consumed only by the reduce tree
sky130_fd_sc_hd__xnor2_2 u1052 (   // SUM_BIT.cell
    .A(g0),
    .B(xsum1),
    .Y(sumbit0)
);

// ---- CARRY_MERGE
sky130_fd_sc_hd__a31o_2 u613 (   // CARRY_MERGE.cell
    .A1(b_reg2),
    .A2(a_reg2),
    .A3(p3_dual),
    .B1(g3),
    .X(carry1)
);

// ---- CARRY_MERGE
sky130_fd_sc_hd__a31o_2 u866 (   // CARRY_MERGE.cell
    .A1(b_reg4),
    .A2(a_reg4),
    .A3(p5_dual),
    .B1(g5),
    .X(carry2)
);

// ---- SUM_BIT
sky130_fd_sc_hd__xor2_2 u634 (   // SUM_BIT.cell
    .A(carry0),
    .B(xsum2),
    .X(sumbit1)
);

// ---- CARRY_MERGE
sky130_fd_sc_hd__a21bo_2 u707 (   // CARRY_MERGE.cell
    .A1(carry0),
    .A2(xsum2),
    .B1_N(g2),
    .X(carry3)
);

// ---- CARRY_MERGE
sky130_fd_sc_hd__a31o_2 u917 (   // CARRY_MERGE.cell
    .A1(carry0),
    .A2(xsum2),
    .A3(xsum3),
    .B1(carry1),
    .X(carry4)
);

// ---- SUM_BIT
sky130_fd_sc_hd__xor2_2 u633 (   // SUM_BIT.cell
    .A(xsum4),
    .B(carry4),
    .X(sumbit2)
);

// ---- CARRY_MERGE
sky130_fd_sc_hd__a31o_2 u635 (   // CARRY_MERGE.cell
    .A1(xsum4),
    .A2(carry4),
    .A3(xsum5),
    .B1(carry2),
    .X(carry5)
);

// ---- CARRY_MERGE
sky130_fd_sc_hd__a21o_2 u781 (   // CARRY_MERGE.cell
    .A1(xsum4),
    .A2(carry4),
    .B1(g4),
    .X(carry6)
);

// ---- SUM_BIT
sky130_fd_sc_hd__xor2_2 u972 (   // SUM_BIT.cell
    .A(xsum3),
    .B(carry3),
    .X(sumbit3)
);

// ---- CARRY_MERGE
sky130_fd_sc_hd__a21boi_2 u622 (   // CARRY_MERGE.cell
    .A1(p6),
    .A2(carry5),
    .B1_N(g6),
    .Y(carry7)
);

// ---- SUM_BIT
sky130_fd_sc_hd__xor2_2 u632 (   // SUM_BIT.cell
    .A(xsum5),
    .B(carry6),
    .X(sumbit4)
);

// ---- SUM_BIT
sky130_fd_sc_hd__xnor2_2 u900 (   // SUM_BIT.cell
    .A(xsum6),
    .B(carry5),
    .Y(sumbit5)
);

// ---- SUM_BIT
sky130_fd_sc_hd__o21bai_2 u623 (   // SUM_BIT.cell
    .A1(p7),
    .A2(carry7),
    .B1_N(g7),
    .Y(sumbit6)
);

// ---- EQ_REDUCE (context): AND-class gate reducing sum/compare bits toward a single equality output
sky130_fd_sc_hd__and4bb_2 u6 (   // EQ_REDUCE.cell
    .A_N(sumbit3),
    .B_N(sumbit1),
    .C(sumbit2),
    .D(sumbit4),
    .X(eq0)
);

// ---- SUM_BIT
sky130_fd_sc_hd__xnor2_2 u975 (   // SUM_BIT.cell
    .A(xsum7),
    .B(carry7),
    .Y(sumbit7)
);

// ---- EQ_REDUCE
sky130_fd_sc_hd__and3_2 u108 (   // EQ_REDUCE.cell
    .A(sumbit5),
    .B(sumbit7),
    .C(sumbit6),
    .X(eq1)
);

// ---- EQ_REDUCE
sky130_fd_sc_hd__and4bb_2 u659 (   // EQ_REDUCE.cell
    .A_N(sumbit0),
    .B_N(xsum0),
    .C(eq1),
    .D(eq0),
    .X(S)
);

endmodule // adder_compare

// 1 enable-gated shift register(s), width 8
module shift_reg_A (
    input  A,
    input  clknet1,
    input  en,
    input  rst_n,
    output a_reg0,
    output a_reg1,
    output a_reg2,
    output a_reg3,
    output a_reg4,
    output a_reg5,
    output a_reg6,
    output a_reg7
);

wire a_nxt0;
wire a_nxt1;
wire a_nxt2;
wire a_nxt3;
wire a_nxt4;
wire a_nxt5;
wire a_nxt6;
wire a_nxt7;

// ---- LOAD_ENABLE_REG [bit 0] (structure): mux2 + flop whose A0 leg is the flop's own Q: the bit holds unless sel steers the load leg in
sky130_fd_sc_hd__mux2_1 u140 (   // LOAD_ENABLE_REG.mux
    .A0(a_reg0),
    .A1(A),
    .S(en),
    .X(a_nxt0)
);
sky130_fd_sc_hd__dfrtp_2 u181 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet1),
    .D(a_nxt0),
    .RESET_B(rst_n),
    .Q(a_reg0)
);

// ---- LOAD_ENABLE_REG [bit 1]
sky130_fd_sc_hd__mux2_1 u339 (   // LOAD_ENABLE_REG.mux
    .A0(a_reg1),
    .A1(a_reg0),
    .S(en),
    .X(a_nxt1)
);
sky130_fd_sc_hd__dfrtp_2 u368 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet1),
    .D(a_nxt1),
    .RESET_B(rst_n),
    .Q(a_reg1)
);

// ---- LOAD_ENABLE_REG [bit 2]
sky130_fd_sc_hd__mux2_1 u234 (   // LOAD_ENABLE_REG.mux
    .A0(a_reg2),
    .A1(a_reg1),
    .S(en),
    .X(a_nxt2)
);
sky130_fd_sc_hd__dfrtp_2 u180 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet1),
    .D(a_nxt2),
    .RESET_B(rst_n),
    .Q(a_reg2)
);

// ---- LOAD_ENABLE_REG [bit 3]
sky130_fd_sc_hd__mux2_1 u137 (   // LOAD_ENABLE_REG.mux
    .A0(a_reg3),
    .A1(a_reg2),
    .S(en),
    .X(a_nxt3)
);
sky130_fd_sc_hd__dfrtp_2 u146 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet1),
    .D(a_nxt3),
    .RESET_B(rst_n),
    .Q(a_reg3)
);

// ---- LOAD_ENABLE_REG [bit 4]
sky130_fd_sc_hd__mux2_1 u138 (   // LOAD_ENABLE_REG.mux
    .A0(a_reg4),
    .A1(a_reg3),
    .S(en),
    .X(a_nxt4)
);
sky130_fd_sc_hd__dfrtp_2 u142 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet1),
    .D(a_nxt4),
    .RESET_B(rst_n),
    .Q(a_reg4)
);

// ---- LOAD_ENABLE_REG [bit 5]
sky130_fd_sc_hd__mux2_1 u210 (   // LOAD_ENABLE_REG.mux
    .A0(a_reg5),
    .A1(a_reg4),
    .S(en),
    .X(a_nxt5)
);
sky130_fd_sc_hd__dfrtp_2 u141 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet1),
    .D(a_nxt5),
    .RESET_B(rst_n),
    .Q(a_reg5)
);

// ---- LOAD_ENABLE_REG [bit 6]
sky130_fd_sc_hd__mux2_1 u139 (   // LOAD_ENABLE_REG.mux
    .A0(a_reg6),
    .A1(a_reg5),
    .S(en),
    .X(a_nxt6)
);
sky130_fd_sc_hd__dfrtp_2 u182 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet1),
    .D(a_nxt6),
    .RESET_B(rst_n),
    .Q(a_reg6)
);

// ---- LOAD_ENABLE_REG [bit 7]
sky130_fd_sc_hd__mux2_1 u274 (   // LOAD_ENABLE_REG.mux
    .A0(a_reg7),
    .A1(a_reg6),
    .S(en),
    .X(a_nxt7)
);
sky130_fd_sc_hd__dfrtp_2 u348 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet1),
    .D(a_nxt7),
    .RESET_B(rst_n),
    .Q(a_reg7)
);

endmodule // shift_reg_A

// 1 enable-gated shift register(s), width 8
module shift_reg_B (
    input  B,
    input  clknet2,
    input  en,
    input  rst_n,
    output b_reg0,
    output b_reg1,
    output b_reg2,
    output b_reg3,
    output b_reg4,
    output b_reg5,
    output b_reg6,
    output b_reg7
);

wire b_nxt0;
wire b_nxt1;
wire b_nxt2;
wire b_nxt3;
wire b_nxt4;
wire b_nxt5;
wire b_nxt6;
wire b_nxt7;

// ---- LOAD_ENABLE_REG [bit 0] (structure): mux2 + flop whose A0 leg is the flop's own Q: the bit holds unless sel steers the load leg in
sky130_fd_sc_hd__mux2_1 u379 (   // LOAD_ENABLE_REG.mux
    .A0(b_reg0),
    .A1(B),
    .S(en),
    .X(b_nxt0)
);
sky130_fd_sc_hd__dfrtp_2 u541 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet2),
    .D(b_nxt0),
    .RESET_B(rst_n),
    .Q(b_reg0)
);

// ---- LOAD_ENABLE_REG [bit 1]
sky130_fd_sc_hd__mux2_1 u378 (   // LOAD_ENABLE_REG.mux
    .A0(b_reg1),
    .A1(b_reg0),
    .S(en),
    .X(b_nxt1)
);
sky130_fd_sc_hd__dfrtp_2 u433 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet2),
    .D(b_nxt1),
    .RESET_B(rst_n),
    .Q(b_reg1)
);

// ---- LOAD_ENABLE_REG [bit 2]
sky130_fd_sc_hd__mux2_1 u369 (   // LOAD_ENABLE_REG.mux
    .A0(b_reg2),
    .A1(b_reg1),
    .S(en),
    .X(b_nxt2)
);
sky130_fd_sc_hd__dfrtp_2 u388 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet2),
    .D(b_nxt2),
    .RESET_B(rst_n),
    .Q(b_reg2)
);

// ---- LOAD_ENABLE_REG [bit 3]
sky130_fd_sc_hd__mux2_1 u603 (   // LOAD_ENABLE_REG.mux
    .A0(b_reg3),
    .A1(b_reg2),
    .S(en),
    .X(b_nxt3)
);
sky130_fd_sc_hd__dfrtp_2 u386 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet2),
    .D(b_nxt3),
    .RESET_B(rst_n),
    .Q(b_reg3)
);

// ---- LOAD_ENABLE_REG [bit 4]
sky130_fd_sc_hd__mux2_1 u418 (   // LOAD_ENABLE_REG.mux
    .A0(b_reg4),
    .A1(b_reg3),
    .S(en),
    .X(b_nxt4)
);
sky130_fd_sc_hd__dfrtp_2 u554 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet2),
    .D(b_nxt4),
    .RESET_B(rst_n),
    .Q(b_reg4)
);

// ---- LOAD_ENABLE_REG [bit 5]
sky130_fd_sc_hd__mux2_1 u596 (   // LOAD_ENABLE_REG.mux
    .A0(b_reg5),
    .A1(b_reg4),
    .S(en),
    .X(b_nxt5)
);
sky130_fd_sc_hd__dfrtp_2 u453 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet2),
    .D(b_nxt5),
    .RESET_B(rst_n),
    .Q(b_reg5)
);

// ---- LOAD_ENABLE_REG [bit 6]
sky130_fd_sc_hd__mux2_1 u426 (   // LOAD_ENABLE_REG.mux
    .A0(b_reg6),
    .A1(b_reg5),
    .S(en),
    .X(b_nxt6)
);
sky130_fd_sc_hd__dfrtp_2 u385 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet2),
    .D(b_nxt6),
    .RESET_B(rst_n),
    .Q(b_reg6)
);

// ---- LOAD_ENABLE_REG [bit 7]
sky130_fd_sc_hd__mux2_1 u404 (   // LOAD_ENABLE_REG.mux
    .A0(b_reg7),
    .A1(b_reg6),
    .S(en),
    .X(b_nxt7)
);
sky130_fd_sc_hd__dfrtp_2 u387 (   // LOAD_ENABLE_REG.ff
    .CLK(clknet2),
    .D(b_nxt7),
    .RESET_B(rst_n),
    .Q(b_reg7)
);

endmodule // shift_reg_B

// clock tree (3 buffers -> 16 flop clock pins)
module clk_tree (
    input  clk,
    output clknet1,
    output clknet2
);

wire clknet0;

// ---- CLOCK_BUFFER (function): clock-tree buffer
sky130_fd_sc_hd__clkbuf_16 u5 (   // CLOCK_BUFFER.buf
    .A(clk),
    .X(clknet0)
);

// ---- CLOCK_BUFFER
sky130_fd_sc_hd__clkbuf_16 u136 (   // CLOCK_BUFFER.buf
    .A(clknet0),
    .X(clknet1)
);

// ---- CLOCK_BUFFER
sky130_fd_sc_hd__clkbuf_16 u443 (   // CLOCK_BUFFER.buf
    .A(clknet0),
    .X(clknet2)
);

endmodule // clk_tree

module blockMatch (
    input  A,
    input  B,
    input  clk,
    input  en,
    input  rst_n,
    output S
);

wire a_reg0;
wire a_reg1;
wire a_reg2;
wire a_reg3;
wire a_reg4;
wire a_reg5;
wire a_reg6;
wire a_reg7;
wire b_reg0;
wire b_reg1;
wire b_reg2;
wire b_reg3;
wire b_reg4;
wire b_reg5;
wire b_reg6;
wire b_reg7;
wire clknet1;
wire clknet2;

adder_compare u_adder_compare (
    .a_reg0(a_reg0),
    .a_reg1(a_reg1),
    .a_reg2(a_reg2),
    .a_reg3(a_reg3),
    .a_reg4(a_reg4),
    .a_reg5(a_reg5),
    .a_reg6(a_reg6),
    .a_reg7(a_reg7),
    .b_reg0(b_reg0),
    .b_reg1(b_reg1),
    .b_reg2(b_reg2),
    .b_reg3(b_reg3),
    .b_reg4(b_reg4),
    .b_reg5(b_reg5),
    .b_reg6(b_reg6),
    .b_reg7(b_reg7),
    .S(S)
);

shift_reg_A u_shift_reg_A (
    .A(A),
    .clknet1(clknet1),
    .en(en),
    .rst_n(rst_n),
    .a_reg0(a_reg0),
    .a_reg1(a_reg1),
    .a_reg2(a_reg2),
    .a_reg3(a_reg3),
    .a_reg4(a_reg4),
    .a_reg5(a_reg5),
    .a_reg6(a_reg6),
    .a_reg7(a_reg7)
);

shift_reg_B u_shift_reg_B (
    .B(B),
    .clknet2(clknet2),
    .en(en),
    .rst_n(rst_n),
    .b_reg0(b_reg0),
    .b_reg1(b_reg1),
    .b_reg2(b_reg2),
    .b_reg3(b_reg3),
    .b_reg4(b_reg4),
    .b_reg5(b_reg5),
    .b_reg6(b_reg6),
    .b_reg7(b_reg7)
);

clk_tree u_clk_tree (
    .clk(clk),
    .clknet1(clknet1),
    .clknet2(clknet2)
);

endmodule // blockMatch
